
spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qqwwqwqwqqwwq/config-repo
          username: 17640396608
          password: My199434.
          basedir: E:/workspace/imooc/SpringClound_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/