
spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qqwwqwqwqqwwq/config-repo
          username: 17640396608
          password: My199434.
          basedir: E:/workspace/imooc/SpringClound_Sell/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:  #actuator
  server:
    port: 8080
  endpoints:
    web:
#      base-path: / #\u9ED8\u8BA4\u662F/actuator \u524D\u7F00\uFF0C\u53EF\u4EE5\u5728\u8FD9\u91CC\u4FEE\u6539
      exposure:
        include: "*"  #\u6253\u5F00\u5168\u90E8\u8BF7\u6C42\u7AEF\u70B9
#        include: refresh,health,info #\u6253\u5F00\u90E8\u5206

