eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
#  开发环境service端警告关闭 默认true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761